name: build-msvc

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: ["win32", "win64"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build
      run: .\ci\build-msvc.ps1 -target ${{ matrix.target }}
